name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to ScratchID! It looks like this is your first Issue reported, so we would like to welcome you."
        pr-message: "Welcome to ScratchID! It looks like this is your first Pull Request reported, so we would like to welcome you."
